### ISSUE TITLE
Archiving allure-python-commons-feedstock

### ISSUE THREAD

**Issue by kenodegard** [conda-forge/allure-python-commons-feedstock#22]
### Comment:

The https://github.com/conda-forge/allure-python-feedstock was recently created (see https://github.com/conda-forge/staged-recipes/pull/23089) which outputs `allure-python-commons` as well as the different testing frameworks integrations (see https://github.com/allure-framework/allure-python).

This resulted in https://github.com/conda-forge/allure-python-feedstock/issues/1 which lead to the fix in https://github.com/conda-forge/feedstock-outputs/pull/48.

To finish this migration to the new feedstock we need to archive this old feedstock.

Opening a request in https://github.com/conda-forge/admin-requests shortly...

**Comment by nsoranzo** [comment]
:+1: Thanks for working on this @kenodegard !
